### ISSUE TITLE
BadUSB BT Connection requires app restart

### ISSUE THREAD

**Issue by Kuzuru** [ClaraCrazy/Flipper-Xtreme#177]
### Describe the bug.

At the moment, working with BadUSB via Bluetooth works with a small bug: When connecting to the flipper via Bluetooth BadUSB APP does not immediately detect the device as expected. You have to re-enter badusb after connecting

### Reproduction

1. Open BadUSB (for example `demo_windows`)
2. `< Config`
3. Select `Connection: BT`
4. Connect to your flipper
5. Approve code
6. ?????
7. GOT: No reaction on the connection
8. Closing `demo_windows`
9. Opening it again and voila! It works

### Anything else?

I recorded it in video just in case it could help: https://youtu.be/uEDYI_rPSa8

**Comment by Willy-JL** [comment]
Works fine here... are you sure you installed v42 after the hotfix?

**Comment by Kuzuru** [comment]
Yep I'm sure. I'd installed v42 from `main` branch from releases tab

**Comment by Kuzuru** [comment]
FW: `XFW-0042_09032023`

**Comment by Willy-JL** [comment]
yeah... exactly... v42 had issues at launch, we fixed them a little after, files are updated, but its not a new release. i suggest you reinstall

**Comment by Kuzuru** [comment]
I guess I can go on and install dev...?

**Comment by Kuzuru** [comment]
Reinstalled FW using this one:
![image](https://user-images.githubusercontent.com/49472529/226710267-69ce510e-364c-4fba-9d10-817e5745cbb8.png)

Unfortunately, reinstalling didn't fix my problem
