### ISSUE TITLE
Error 4294967295

### ISSUE THREAD

**Issue by KaliStudio** [ClaraCrazy/Flipper-Xtreme#557]
### Describe the bug.

I get an error when compiling :  Error 4294967295

### Reproduction

I re-downloaded the github: git clone --recursive --jobs 8 https://github.com/Flipper-XFW/Xtreme-Firmware.git
Build firmware using Flipper Build Tool: ./fbt

### Logs

```Text
./fbt COMPACT=1 DEBUG=0 updater_package

fbt: warning: Failed parsing manifest 'C:\Xtreme-Firmware\applications\external\mifare_nested\application.fam' : Invalid appid '.mifare_nested'. Must match regex 're.compile('^[a-z0-9_]+$')'
LoadAppManifest, line 132, in file "C:\Xtreme-Firmware\scripts\fbt_tools\fbt_apps.py"

fbt: warning: Failed parsing manifest 'C:\Xtreme-Firmware\applications\external\mifare_nested\application.fam' : Invalid appid '.mifare_nested'. Must match regex 're.compile('^[a-z0-9_]+$')'
LoadAppManifest, line 132, in file "C:\Xtreme-Firmware\scripts\fbt_tools\fbt_apps.py"
        PROTO   assets\protobuf\application.proto
        CC      applications\main\subghz\scenes\subghz_scene_save_name.c
        CC      applications\main\subghz\scenes\subghz_scene_save_success.c
        CC      applications\main\subghz\scenes\subghz_scene_saved.c
        CC      applications\main\subghz\scenes\subghz_scene_saved_menu.c
        CC      applications\main\subghz\scenes\subghz_scene_saved_show_gps.c
        CC      applications\main\subghz\scenes\subghz_scene_set_cnt.c
        CC      applications\main\subghz\scenes\subghz_scene_set_fix.c
        CC      applications\main\subghz\scenes\subghz_scene_set_seed.c
        CC      applications\main\subghz\scenes\subghz_scene_set_type.c
        CC      applications\main\subghz\scenes\subghz_scene_show_error.c
        CC      applications\main\subghz\scenes\subghz_scene_show_error_sub.c
        CC      applications\main\subghz\scenes\subghz_scene_show_gps.c
        CC      applications\main\subghz\scenes\subghz_scene_start.c
        CC      applications\main\subghz\scenes\subghz_scene_transmitter.c
scons: *** [build\f7-firmware-C\assets\compiled\application.pb.c] Error 4294967295
        CC      applications\main\subghz\views\receiver.c

********** FBT ERRORS **********
build\f7-firmware-C\assets\compiled\application.pb.c: Error 4294967295
PS C:\Xtreme-Firmware>
```

### Anything else?

in windows 11

**Comment by WillyJL** [comment]
are you sure you cloned again? that looks like an error from un-clean build environment, after a change from upstream toolchain

**Comment by KaliStudio** [comment]
I just re-cloned it now:
```

PS C:\> git clone --recursive --jobs 8 https://github.com/Flipper-XFW/Xtreme-Firmware.git
Cloning into 'Xtreme-Firmware'...
remote: Enumerating objects: 144296, done.
remote: Counting objects: 100% (4161/4161), done.
remote: Compressing objects: 100% (1345/1345), done.
remote: Total 144296 (delta 2882), reused 4021 (delta 2754), pack-reused 140135
Receiving objects: 100% (144296/144296), 596.69 MiB | 36.88 MiB/s, done.
Resolving deltas: 100% (97466/97466), done.
Updating files: 100% (4182/4182), done.
Submodule 'applications/external' (https://github.com/Flipper-XFW/Xtreme-Apps.git) registered for path 'applications/external'
Submodule 'assets/protobuf' (https://github.com/flipperdevices/flipperzero-protobuf.git) registered for path 'assets/protobuf'
Submodule 'lib/FreeRTOS-Kernel' (https://github.com/FreeRTOS/FreeRTOS-Kernel.git) registered for path 'lib/FreeRTOS-Kernel'
Submodule 'lib/cxxheaderparser' (https://github.com/robotpy/cxxheaderparser.git) registered for path 'lib/cxxheaderparser'
Submodule 'lib/heatshrink' (https://github.com/flipperdevices/heatshrink.git) registered for path 'lib/heatshrink'
Submodule 'lib/libusb_stm32' (https://github.com/flipperdevices/libusb_stm32.git) registered for path 'lib/libusb_stm32'
Submodule 'lib/littlefs' (https://github.com/littlefs-project/littlefs.git) registered for path 'lib/littlefs'
Submodule 'lib/mbedtls' (https://github.com/Mbed-TLS/mbedtls.git) registered for path 'lib/mbedtls'
Submodule 'lib/microtar' (https://github.com/amachronic/microtar.git) registered for path 'lib/microtar'
Submodule 'lib/mlib' (https://github.com/P-p-H-d/mlib.git) registered for path 'lib/mlib'
Submodule 'lib/nanopb' (https://github.com/nanopb/nanopb.git) registered for path 'lib/nanopb'
Submodule 'lib/st_cmsis_device_wb' (https://github.com/STMicroelectronics/cmsis_device_wb) registered for path 'lib/stm32wb_cmsis'
Submodule 'lib/stm32wb_copro' (https://github.com/flipperdevices/stm32wb_copro.git) registered for path 'lib/stm32wb_copro'
Submodule 'lib/stm32wbxx_hal_driver' (https://github.com/STMicroelectronics/stm32wbxx_hal_driver) registered for path 'lib/stm32wb_hal'
Cloning into 'C:/Xtreme-Firmware/applications/external'...
remote: Enumerating objects: 88662, done.
remote: Counting objects: 100% (22941/22941), done.
remote: Compressing objects: 100% (9746/9746), done.
remote: Total 88662 (delta 13024), reused 22665 (delta 12784), pack-reused 65721
Receiving objects: 100% (88662/88662), 922.79 MiB | 25.43 MiB/s, done.
Resolving deltas: 100% (56094/56094), done.
Cloning into 'C:/Xtreme-Firmware/assets/protobuf'...
remote: Enumerating objects: 290, done.
remote: Counting objects: 100% (174/174), done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 290 (delta 124), reused 127 (delta 89), pack-reused 116
Receiving objects: 100% (290/290), 59.53 KiB | 2.83 MiB/s, done.
Resolving deltas: 100% (165/165), done.
Cloning into 'C:/Xtreme-Firmware/lib/heatshrink'...
remote: Enumerating objects: 393, done.
remote: Counting objects: 100% (85/85), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 393 (delta 74), reused 71 (delta 71), pack-reused 308
Receiving objects: 100% (393/393), 146.08 KiB | 3.84 MiB/s, done.
Resolving deltas: 100% (244/244), done.
Cloning into 'C:/Xtreme-Firmware/lib/cxxheaderparser'...
remote: Enumerating objects: 1066, done.
remote: Counting objects: 100% (474/474), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 1066 (delta 396), reused 393 (delta 342), pack-reused 592
Receiving objects: 100% (1066/1066), 310.70 KiB | 5.36 MiB/s, done.
Resolving deltas: 100% (704/704), done.
Cloning into 'C:/Xtreme-Firmware/lib/libusb_stm32'...
remote: Enumerating objects: 1741, done.
remote: Counting objects: 100% (331/331), done.
remote: Compressing objects: 100% (98/98), done.
remote: Total 1741 (delta 263), reused 263 (delta 232), pack-reused 1410
Receiving objects: 100% (1741/1741), 1013.96 KiB | 11.27 MiB/s, done.
Resolving deltas: 100% (1098/1098), done.
Cloning into 'C:/Xtreme-Firmware/lib/microtar'...
remote: Enumerating objects: 252, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 252 (delta 25), reused 25 (delta 25), pack-reused 224
Receiving objects: 100% (252/252), 51.85 KiB | 2.47 MiB/s, done.
Resolving deltas: 100% (143/143), done.
Cloning into 'C:/Xtreme-Firmware/lib/littlefs'...
remote: Enumerating objects: 8488, done.
remote: Counting objects: 100% (2595/2595), done.
remote: Compressing objects: 100% (666/666), done.
remote: Total 8488 (delta 2016), reused 2401 (delta 1922), pack-reused 5893
Receiving objects: 100% (8488/8488), 5.80 MiB | 20.56 MiB/s, done.
Resolving deltas: 100% (6269/6269), done.
Cloning into 'C:/Xtreme-Firmware/lib/stm32wb_cmsis'...
remote: Enumerating objects: 492, done.
remote: Counting objects: 100% (492/492), done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 492 (delta 359), reused 445 (delta 312), pack-reused 0
Receiving objects: 100% (492/492), 467.29 KiB | 3.99 MiB/s, done.
Resolving deltas: 100% (359/359), done.
Cloning into 'C:/Xtreme-Firmware/lib/nanopb'...
remote: Enumerating objects: 8981, done.
remote: Counting objects: 100% (419/419), done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 8981 (delta 242), reused 336 (delta 221), pack-reused 8562
Receiving objects: 100% (8981/8981), 4.21 MiB | 3.80 MiB/s, done.
Resolving deltas: 100% (5753/5753), done.
Cloning into 'C:/Xtreme-Firmware/lib/mlib'...
remote: Enumerating objects: 14723, done.
remote: Counting objects: 100% (4218/4218), done.
remote: Compressing objects: 100% (1221/1221), done.
remote: Total 14723 (delta 3074), reused 4100 (delta 2973), pack-reused 10505
Receiving objects: 100% (14723/14723), 8.15 MiB | 10.69 MiB/s, done.
Resolving deltas: 100% (10689/10689), done.
Cloning into 'C:/Xtreme-Firmware/lib/stm32wb_hal'...
remote: Enumerating objects: 1154, done.
remote: Counting objects: 100% (1154/1154), done.
remote: Compressing objects: 100% (889/889), done.
remote: Total 1154 (delta 929), reused 468 (delta 248), pack-reused 0
Receiving objects: 100% (1154/1154), 1.70 MiB | 9.45 MiB/s, done.
Resolving deltas: 100% (929/929), done.
Cloning into 'C:/Xtreme-Firmware/lib/stm32wb_copro'...
remote: Enumerating objects: 1837, done.
remote: Counting objects: 100% (213/213), done.
remote: Compressing objects: 100% (170/170), done.
remote: Total 1837 (delta 40), reused 134 (delta 28), pack-reused 1624
Receiving objects: 100% (1837/1837), 73.96 MiB | 20.39 MiB/s, done.
Resolving deltas: 100% (950/950), done.
Cloning into 'C:/Xtreme-Firmware/lib/FreeRTOS-Kernel'...
remote: Enumerating objects: 172706, done.
remote: Counting objects: 100% (496/496), done.
remote: Compressing objects: 100% (301/301), done.
remote: Total 172706 (delta 286), reused 334 (delta 164), pack-reused 172210
Receiving objects: 100% (172706/172706), 114.93 MiB | 20.22 MiB/s, done.
Resolving deltas: 100% (124067/124067), done.
Cloning into 'C:/Xtreme-Firmware/lib/mbedtls'...
remote: Enumerating objects: 238817, done.
remote: Total 238817 (delta 0), reused 0 (delta 0), pack-reused 238817
Receiving objects: 100% (238817/238817), 114.39 MiB | 23.75 MiB/s, done.
Resolving deltas: 100% (186385/186385), done.
Submodule path 'applications/external': checked out 'efa5ce68286038e37e41f3bcb835b0d094491def'
Submodule path 'assets/protobuf': checked out '1956b83bba99313ee8d8386e5d35d0549341ca26'
Submodule path 'lib/FreeRTOS-Kernel': checked out 'def7d2df2b0506d3d249334974f51e427c17a41c'
Submodule 'ThirdParty/FreeRTOS-Kernel-Community-Supported-Ports' (https://github.com/FreeRTOS/FreeRTOS-Kernel-Community-Supported-Ports) registered for path 'lib/FreeRTOS-Kernel/portable/ThirdParty/Community-Supported-Ports'
Submodule 'ThirdParty/FreeRTOS-Kernel-Partner-Supported-Ports' (https://github.com/FreeRTOS/FreeRTOS-Kernel-Partner-Supported-Ports) registered for path 'lib/FreeRTOS-Kernel/portable/ThirdParty/Partner-Supported-Ports'
Cloning into 'C:/Xtreme-Firmware/lib/FreeRTOS-Kernel/portable/ThirdParty/Community-Supported-Ports'...
remote: Enumerating objects: 79, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 79 (delta 23), reused 64 (delta 18), pack-reused 0
Receiving objects: 100% (79/79), 46.39 KiB | 2.11 MiB/s, done.
Resolving deltas: 100% (23/23), done.
Cloning into 'C:/Xtreme-Firmware/lib/FreeRTOS-Kernel/portable/ThirdParty/Partner-Supported-Ports'...
remote: Enumerating objects: 70, done.
remote: Counting objects: 100% (70/70), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 70 (delta 24), reused 48 (delta 15), pack-reused 0
Receiving objects: 100% (70/70), 46.05 KiB | 2.71 MiB/s, done.
Resolving deltas: 100% (24/24), done.
Submodule path 'lib/FreeRTOS-Kernel/portable/ThirdParty/Community-Supported-Ports': checked out '4273ca3211b99914f31518378fb590fbff064953'
Submodule path 'lib/FreeRTOS-Kernel/portable/ThirdParty/Partner-Supported-Ports': checked out '3f9c99a682c5c796bb7eb89fd9c4385688fce27a'
Submodule path 'lib/cxxheaderparser': checked out 'ba4222560fc1040670b1a917d5d357198e8ec5d6'
Submodule path 'lib/heatshrink': checked out '7398ccc91652a33483245200cfa1a83b073bc206'
Submodule path 'lib/libusb_stm32': checked out '6ca2857519f996244f7b324dd227fdf0a075fffb'
Submodule path 'lib/littlefs': checked out '611c9b20db2b99faee261daa7cc9bbe175d3eaca'
Submodule path 'lib/mbedtls': checked out 'edb8fec9882084344a314368ac7fd957a187519c'
Submodule path 'lib/microtar': checked out '1e921369b2c92bb219fcef84a37d4d2347794c0f'
Submodule path 'lib/mlib': checked out '62c8ac3e5d4a7a4f8757328e7a80286fde2686b6'
Submodule path 'lib/nanopb': checked out 'afc499f9a410fc9bbf6c9c48cdd8d8b199d49eb4'
Submodule path 'lib/stm32wb_cmsis': checked out 'd1b860584dfe24d40d455ae624ed14600dfa93c9'
Submodule path 'lib/stm32wb_copro': checked out 'd8a6f1feb0ebb6798c44162c6ae5ea743f90f3df'
Submodule 'scripts' (https://github.com/flipperdevices/stm32wb_copro_scripts) registered for path 'lib/stm32wb_copro/scripts'
Cloning into 'C:/Xtreme-Firmware/lib/stm32wb_copro/scripts'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 10 (delta 0), reused 10 (delta 0), pack-reused 0
Receiving objects: 100% (10/10), 4.24 KiB | 4.24 MiB/s, done.
Submodule path 'lib/stm32wb_copro/scripts': checked out '781464e628eb694b4c98a79ab524c293f527fc8d'
Submodule path 'lib/stm32wb_hal': checked out 'cfd0dd258cb031c95b2b2d6d04c19f9f625fe3e8'

./fbt COMPACT=1 DEBUG=0 updater_package
Downloading Windows toolchain..done!


    Répertoire : C:\Xtreme-Firmware


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        13/02/2024     07:44                toolchain
Extracting Windows toolchain..moving..done!
Cleaning up temporary files..done!



fbt: warning: Failed parsing manifest 'C:\Xtreme-Firmware\applications\external\mifare_nested\application.fam' : Invalid appid '.mifare_nested'. Must match regex 're.compile('^[a-z0-9_]+$')'
LoadAppManifest, line 132, in file "C:\Xtreme-Firmware\scripts\fbt_tools\fbt_apps.py"

fbt: warning: Failed parsing manifest 'C:\Xtreme-Firmware\applications\external\mifare_nested\application.fam' : Invalid appid '.mifare_nested'. Must match regex 're.compile('^[a-z0-9_]+$')'
LoadAppManifest, line 132, in file "C:\Xtreme-Firmware\scripts\fbt_tools\fbt_apps.py"
        ICONS   build\icons\assets_icons.c
        PROTO   assets\protobuf\application.proto
        DOLPHIN blocking
        DOLPHIN internal
2024-02-13 07:45:00,930 [INFO] Processing Dolphin sources
2024-02-13 07:45:00,930 [INFO] Processing Dolphin sources
2024-02-13 07:45:00,930 [INFO] Loading data
2024-02-13 07:45:00,930 [INFO] Loading data
2024-02-13 07:45:00,930 [INFO] Loading directory assets\dolphin\internal
2024-02-13 07:45:00,930 [INFO] Loading directory assets\dolphin\blocking
2024-02-13 07:45:00,931 [INFO] Packing
2024-02-13 07:45:00,932 [INFO] Packing
        APPS    build\f7-firmware-C\applications\applications.c
        CC      applications\main\archive\helpers\archive_apps.c
        CC      applications\main\archive\helpers\archive_browser.c
        CC      applications\main\archive\helpers\archive_favorites.c
        CC      applications\main\archive\helpers\favorite_timeout.c
        CC      applications\main\archive\scenes\archive_scene.c
        CC      applications\main\archive\scenes\archive_scene_browser.c
        CC      applications\main\archive\scenes\archive_scene_delete.c
        CC      applications\main\archive\scenes\archive_scene_info.c
        CC      applications\main\archive\scenes\archive_scene_new_dir.c
        CC      applications\main\archive\scenes\archive_scene_rename.c
        CC      applications\main\archive\scenes\archive_scene_search.c
        CC      applications\main\archive\archive.c
2024-02-13 07:45:01,392 [INFO] Complete
2024-02-13 07:45:01,392 [INFO] Complete
        CC      applications\main\ibutton\ibutton_cli.c
        CC      applications\main\infrared\infrared_brute_force.c
        CC      applications\main\infrared\infrared_cli.c
        CC      applications\main\infrared\infrared_signal.c
Traceback (most recent call last):
  File "C:\Xtreme-Firmware\lib\nanopb\generator\nanopb_generator.py", line 51, in <module>
    from .proto import nanopb_pb2
ImportError: attempted relative import with no known parent package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Xtreme-Firmware\lib\nanopb\generator\nanopb_generator.py", line 72, in <module>
    import proto.nanopb_pb2 as nanopb_pb2
ModuleNotFoundError: No module named 'proto.nanopb_pb2'
        CC      applications\main\archive\views\archive_browser_view.c
scons: *** [build\f7-firmware-C\assets\compiled\application.pb.c] Error 1

********** FBT ERRORS **********
build\f7-firmware-C\assets\compiled\application.pb.c: Error 1
```

**Comment by vollukas** [comment]
I have same issue in Windows 10, but slightly different errors 
![image](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/24632372/353fefdb-135a-4fdd-a24c-cb70e075b434)
![image](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/24632372/847d6679-8f24-4e0d-a2f8-f1ecfd2cef0e)
![image](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/24632372/afa8746a-3cca-4243-a787-a5327e5103a0)
![image](https://github.com/Flipper-XFW/Xtreme-Firmware/assets/24632372/c349dd13-166d-4874-93eb-152cf2f2f455)

**Comment by WillyJL** [comment]
@vollukas issue has been acknowledged by hedger from ofw, will be fixed soon by them.

as for @KaliStudio's, im not entirely sure. i see you are the same person that reported the toolchain not supported issue to ofw, but that is a different error than what you reported to us here. i hope that the protobuf issue you have here is related to the toolchain not supported one that is being worked on.

**Comment by KaliStudio** [comment]
Bonjour, oui, j'ai eu différents problèmes et j'ai posté aux endroits respectifs d'où venait le problème.

> @vollukasLe problème a été reconnu par hedger d'Oww et sera bientôt résolu par eux.
> 
> pour ce qui est de@KaliStudio's, je ne suis pas entièrement sûr. Je vois que vous êtes la même personne qui a signalé le problème de la chaîne d'outils non prise en charge, mais il s'agit d'une erreur différente de celle que vous nous avez signalée ici. J'espère que le problème de protobuf que vous avez ici est lié à la chaîne d'outils non prise en charge sur laquelle vous travaillez.

**Comment by eried** [comment]
I have this same error @KaliStudio found a solution?

**Comment by WillyJL** [comment]
its fixed in dev branch

**Comment by eried** [comment]
oh, strange the bug is back on latest dev on flipper-devices unmodded firmware (for video game module)

**Comment by WillyJL** [comment]
our dev branch includes the work in progress fix for this issue flipperdevices/flipperzero-firmware#3451, which is not yet merged into ofw
