### ISSUE TITLE
Bug in lock screen

### ISSUE THREAD

**Issue by WPTP** [ClaraCrazy/Flipper-Xtreme#70]
When in the screen saver mode, you can push up to get lock options. The "Lock with pin + off" does not work. Tried multiple times & ways still doesn't work.

**Comment by ClaraCrazy** [comment]
This is long known and documented in our Server and fixed in the next release.

**Comment by WPTP** [comment]
Oh ok didn't know was still a problem, because on previous version it was partly working for me. Don't know if I did something different or just got lucky.
